<?php
/** op-unit-crawler:/sample/login/success.phtml
 *
 * @created   2020-02-02
 * @version   1.0
 * @package   op-unit-crawler
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

?>
<section style="margin:1em;">
	<p>Login is successful.</p>
	<p><a href="../private">private page is here</a></p>
</section>
