<?php
/** op-unit-crawler:/sample/private/index.phtml
 *
 * @created   2020-02-02
 * @version   1.0
 * @package   op-unit-crawler
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;
?>
<section style="margin:1em;">
	<h1>Welcome to members only page</h1>
	<p>Username: <?= $_SESSION['username'] ?></p>
	<p><a href="../logout">logout</a></p>
</section>
