<?php
/** op-unit-crawler:/sample/index.phtml
 *
 * @created   2020-02-02
 * @version   1.0
 * @package   op-unit-crawler
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	...
$count = $_SESSION['count'] ?? 0;
$count++;
$_SESSION['count'] = $count;

?>
<?php include('breadcrumbs.phtml') ?>
<section>
	<p>Count: <?= $count ?> </p>
	<ul>
		<li><a href="http://<?= $_SERVER['HTTP_HOST'] ?>">FQDN</a></li>
		<li><a href="/">Document root</a></li>
		<li><a href="..">parent path</a></li>
		<li><a href="../">parent directory</a></li>
		<li><a href="../_testcase">parent relative path</a></li>
		<li><a href="../_testcase/">parent relative directory</a></li>
		<li><a href="../_testcase/index.html">parent relative file</a></li>
		<li><a href="../../">parent of parent directory</a></li>
		<li><a href="login">LOGIN</a></li>
		<li><a href="private">Private</a></li>
		<li><a href="./charset/">charset</a></li>
		<li><a href="">href is empty.</a></li>
		<li><a>href has not been exists. (fake)</a></li>
		<li><a href="transfer.html">Transfer URL</a></li>
		<li><a href="referer.html">HTTP Referer</a></li>
		<li><a href="useragent.html">HTTP User-Agent</a></li>
		<li><a href="timestamp.html">Timestamp</a></li>
		<li><a href="http://example.com">http://example.com</a></li>
		<li><a href="https://example.com">https://example.com</a></li>
		<li><a href="//example.com">//example.com</a></li>
		<li><a href="./テスト">./テスト</a></li>
	</ul>
</section>
